load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tunnel",
    srcs = [
        "conn.go",
        "tls.go",
        "tunnel.go",
    ],
    importpath = "github.com/openconfig/grpctunnel/tunnel",
    visibility = ["//visibility:public"],
    deps = [
        "//bidi",
        "//proto/tunnel",
        "@com_github_cenkalti_backoff_v4//:backoff",
        "@openconfig_gnmi//errlist",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//peer",
    ],
)

go_test(
    name = "tunnel_test",
    srcs = ["tunnel_test.go"],
    embed = [":tunnel"],
    deps = [
        "//proto/tunnel",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//peer",
    ],
)
