load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "dialer",
    srcs = ["dialer.go"],
    importpath = "github.com/openconfig/grpctunnel/dialer",
    visibility = ["//visibility:public"],
    deps = [
        "//tunnel",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_test(
    name = "dialer_test",
    srcs = ["dialer_test.go"],
    embed = [":dialer"],
    deps = [
        "//proto/tunnel",
        "//tunnel",
        "@org_golang_google_grpc//:grpc",
    ],
)
