load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "bidi",
    srcs = ["bidi.go"],
    importpath = "github.com/openconfig/grpctunnel/bidi",
    visibility = ["//visibility:public"],
)

go_test(
    name = "bidi_test",
    srcs = ["bidi_test.go"],
    embed = [":bidi"],
)
