load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "client_lib",
    srcs = ["client.go"],
    importpath = "github.com/openconfig/grpctunnel/cmd/client",
    visibility = ["//visibility:private"],
    deps = [
        "//bidi",
        "//proto/tunnel",
        "//tunnel",
        "@com_github_cenkalti_backoff_v4//:backoff",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "client",
    embed = [":client_lib"],
    visibility = ["//visibility:public"],
)
